# Generated by Django 6.0.3 on 2026-03-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='author',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='startup',
            name='comments_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='startup',
            name='external_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='startup',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='startup',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='startup',
            name='source',
            field=models.CharField(choices=[('hn', 'HackerNews'), ('yc', 'YCombinator'), ('ph', 'ProductHunt')], max_length=20),
        ),
    ]
