# Generated by Django 6.0.3 on 2026-03-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('hn', 'HackerNews'), ('ph', 'GitHub AI'), ('all', 'All Sources')], max_length=20)),
                ('status', models.CharField(default='running', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('fetched_count', models.IntegerField(default=0)),
                ('created_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
            ],
        ),
    ]
